version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=2638543
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    links:
      - "db:database"
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  redis:
    image: redis
    ports:
      - '6379:6379'
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./config/redis:/usr/local/etc/redis

  celery:
    build:
      context: .
    environment:
      - ALLOWED_HOSTS=['*']
    ports: [ ]
    volumes:
      - ./project/:/usr/src/app/
    depends_on:
      redis:
        condition: service_healthy
      api:
        condition: service_started

volumes:
  db:
    driver: local
  redis:
    driver: local
